local mod = require("core/mods")

mod.hook.register("script_pre_init", "txooo init", function()
    params:add_group("TXOOO", 22)
    params:add_separator("GLOBAL")
    params:add_number("txooo_clock_ppqn", "clock ppqn", 1, 16, 4)
    for i = 1, 4 do
        params:add_separator("CHANNEL " .. i)
        params:add_number("txooo_" .. i .. "_lfo_depth", "lfo depth ", 0, 100, 0)
        params:set_action("txooo_" .. i .. "_lfo_depth", function(value)
            crow.ii.txo.cv(i, value / 10)
        end)
        params:add_number("txooo_" .. i .. "_lfo_rate", "lfo rate ", 0, 100, 0)
        params:set_action("txooo_" .. i .. "_lfo_rate", function(value)
            crow.ii.txo.osc_lfo(i, value * 10)
        end)
        params:add_number("txooo_" .. i .. "_lfo_shape", "lfo shape ", 0, 100, 0)
        params:set_action("txooo_" .. i .. "_lfo_shape", function(value)
            crow.ii.txo.osc_wave(i, value * 100)
        end)
        params:add_number("txooo_" .. i .. "_clock_rate", "clock rate ", 1, 64, 1)
        clock.run(function()
            while true do
                local rate = params:get("txooo_" .. i .. "_clock_rate")
                local ppqn = params:get("txooo_clock_ppqn")
                crow.ii.txo.tr_pulse(i)
                clock.sync(rate / ppqn)
            end
        end)
    end
end)
